name: Publish

on:
  # schedule:
  #   - cron: '0 */12 * * 1-5'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'publish'
  cancel-in-progress: true

jobs:
  select_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the latest release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const getLatestRelease = require('./scripts/getLatestRelease.js');
            await getLatestRelease({ github, context, core, workspace: "${{ github.workspace }}" });
    
      - name: DEBUG Artifact Variables
        run: |
          echo "DEBUG: Release Name: $RELEASE_NAME";
          echo "DEBUG: Release Draft: $RELEASE_DRAFT";
          echo "DEBUG: Release Prerelease: $RELEASE_PRERELEASE";
          echo "DEBUG: Release Artifact: $RELEASE_ARTIFACT";
          echo "DEBUG: Artifact Path: $RELEASE_ARTIFACT_PATH";
          echo "DEBUG: Artifact Size: $RELEASE_ARTIFACT_SIZE";
          echo "DEBUG: Artifact Basename: $RELEASE_ARTIFACT_BASENAME";
          echo "DEBUG: Artifact filename: $RELEASE_ARTIFACT_FILENAME";

      - name: Extract the release artifact
        run: |
          mkdir -p ${{ github.workspace }}/dist;
          tar -C ${{ github.workspace }}/dist -xczf $RELEASE_ARTIFACT_FILENAME;
