name: Publish

on:
  # schedule:
  #   - cron: '0 */12 * * 1-5'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'publish'
  cancel-in-progress: true

jobs:
  select_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = await github.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: "sceneforge",
            });
            console.log(JSON.stringify(result, null, 2));
