name: Publish

on:
  # schedule:
  #   - cron: '0 */12 * * 1-5'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'publish'
  cancel-in-progress: true

jobs:
  select_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the latest release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const getLatestRelease = require('./scripts/getLatestRelease.js');
            await getLatestRelease({ github, context, core, workspace: "${{ github.workspace }}" });
    
      - name: DEBUG Artifact Variables
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('DEBUG: Artifact Path:', process.env.artifact_path);
            console.log('DEBUG: Artifact Size:', process.env.artifact_size);
            console.log('DEBUG: Artifact Basename:', process.env.artifact_basename);
            console.log('DEBUG: Artifact filename:', process.env.artifact_filename);
